FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Uppbeat.Api/Uppbeat.Api.csproj", "src/Uppbeat.Api/"]
RUN dotnet restore "src/Uppbeat.Api/Uppbeat.Api.csproj"
COPY . .
WORKDIR "/src/src/Uppbeat.Api"
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "Uppbeat.Api.dll"]